EWasteManagement/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp.urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include(myapp.urls,namespace="myapp")),
]

myapp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
<<<<<<< HEAD
urlpatterns = [
    path('',views.index,name='index'),
    path('cart.html',views.cart,name='cart'),
    path('checkout.html',views.checkout,name='checkout'),
    path('shop.html',views.shop,name='shop'),
    path('single-product.html',views.single,name='single-product'),
    ]
=======

app_name = "myapp"

urlpatterns = [
     
     path('index/',views.index,name='index'),
     path('cart/',views.cart,name='cart'),
     path('checkout/',views.checkout,name='checkout'),
     path('shop/<field>/<value>/',views.shop,name='shop'),
     path('single-product/<id>/<catageory>/',views.singleproduct,name='single-product'),
     path('signup/',views.signup,name='signup'),
     path('signin/',views.signin,name='signin'),
     path('signout/',views.signout,name='signout'),
     path('add_to_cart/<int:id>/',views.add_to_card,name='add_to_card'),
     path('item_clear/<int:id>/',views.item_clear,name='item_clear'),
     path('cart_clear/',views.cart_clear,name='cart_clear'),
     path('addProduct/',views.addProduct,name='addProduct'),
     path('search/',views.search,name='foo-search'),
     path('wishlist/<id>/',views.wishlist,name='wishlist'),
     path('showWishlist/',views.show_wishlist,name='showWishlist'),
     path('place_order/',views.place_order,name='place_order'),
     path('',views.index,name='index'),   
    ]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()    
>>>>>>> 6398115 (yes)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
{%load static%}
    <!-- Google Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,700,600' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>
    
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %} ">
    
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
</head>
<body>

    {% include 'header.html' %}
    {% block content %}


    {% endblock content %}
    {% include 'footer.html' %}


    <script src="https://code.jquery.com/jquery.min.js"></script>
    <!-- Bootstrap JS form CDN -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <!-- jQuery sticky menu -->
    <script src="{%static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.sticky.js' %}"></script>
    <!-- jQuery easing -->
    <script src="{% static 'js/jquery.easing.1.3.min.js' %}"></script>
    <!-- Main Script -->
    <script src="{% static 'js/main.js' %}"></script>

     {% block jquery %}
    <!-- Latest jQuery form server -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    
    <!-- Bootstrap JS form CDN -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
   
   
    <!-- Slider -->
    <script type="text/javascript" src="{% static 'js/bxslider.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/script.slider.js' %}"></script>


     

    {% endblock %}   




</body>
</html>

templates/footer.html
 <div class="footer-top-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <div class="footer-about-us">
                        <h2>Go<span>Green</span></h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis sunt id doloribus vero quam laborum quas alias dolores blanditiis iusto consequatur, modi aliquid eveniet eligendi iure eaque ipsam iste, pariatur omnis sint! Suscipit, debitis, quisquam. Laborum commodi veritatis magni at?</p>
                        <div class="footer-social">
                            
                        </div>
                    </div>
                </div>
                
                <div class="col-md-3 col-sm-6">
                    <div class="footer-menu">
                        <h2 class="footer-wid-title">User Navigation </h2>
                        <ul>
                            <li><a href="#">My account</a></li>
                            <li><a href="#">Order history</a></li>
                            <li><a href="#">Wishlist</a></li>
                            <li><a href="#">Become a Seller</a></li>
                            <li><a href="#">Go-Green</a></li>
                        </ul>                        
                    </div>
                </div>
                
                <div class="col-md-3 col-sm-6">
                    <div class="footer-menu">
                        <h2 class="footer-wid-title">Categories</h2>
                        <ul>
                            <li><a href="#">Mobile Phone</a></li>
                            <li><a href="#">Home accesseries</a></li>
                            <li><a href="#">LED TV</a></li>
                            <li><a href="#">Computer & accesseries</a></li>
                            <li><a href="#">Kitchen appliance</a></li>
                        </ul>                        
                    </div>
                </div>
                
                <div class="col-md-3 col-sm-6">
                    
                </div>
            </div>
        </div>
    </div> <!-- End footer top area -->
    
    <div class="footer-bottom-area">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="copyright">
                        <p>&copy; 2021 @ All Rights Reserved. <a href="http://www.freshdesignweb.com" target="_blank">freshDesignweb.com</a></p>
                    </div>
                </div>
                
                <div class="col-md-4">
                    <div class="footer-card-icon">
                        <i class="fa fa-cc-discover"></i>
                        <i class="fa fa-cc-mastercard"></i>
                        <i class="fa fa-cc-paypal"></i>
                        <i class="fa fa-cc-visa"></i>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End footer bottom are

templates/header.html
{% load static %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
 <div class="header-area">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="user-menu">
                        <ul>
                            <li><a href="#"><i class="fa fa-user"></i> My Account</a></li>
                            <li><a href="{% url 'myapp:showWishlist' %}"><i class="fa fa-heart"></i> Wishlist</a></li>
                            <li><a href="{% url 'myapp:cart'%}"><i class="fa fa-user"></i> My Cart</a></li>
                            <li><a href="{% url 'myapp:checkout' %}"><i class="fa fa-user"></i> Checkout</a></li>
                            {%if user.is_authenticated %}
                            <li><a href="{%url 'myapp:signin'%}"><i class="fa fa-user"></i>Hello, {{user.username}}</a></li>
                            <li><a href="{%url 'myapp:signout'%}"><i class="fa fa-user"></i>Logout</a></li>
                            {%else%}
                            <li><a href="{%url 'myapp:signup'%}"><i class="fa fa-user"></i> Signup</a></li>
                            <li><a href="{%url 'myapp:signin'%}"><i class="fa fa-user"></i> Login</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
                
                <div class="col-md-4">
                    <div class="header-right">
                        <ul class="list-unstyled list-inline">
                            <li class="dropdown dropdown-small">
                                <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" href="#"><span class="key">currency :</span><span class="value">USD </span><b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">USD</a></li>
                                    <li><a href="#">INR</a></li>
                                    <li><a href="#">GBP</a></li>
                                </ul>
                            </li>

                            <li class="dropdown dropdown-small">
                                <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" href="#"><span class="key">language :</span><span class="value">English </span><b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">English</a></li>
                                    <li><a href="#">French</a></li>
                                    <li><a href="#">German</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End header area -->
    
    <div class="site-branding-area">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="logo">
                        <h1><a href="{% url 'myapp:cart' %}"><img src="{% static 'img/logo.png' %}"></a></h1>
                    </div>
-                </div>
                
                
                <div class="col-sm-6">
                    <div class="shopping-item">
                        <a href="{% url 'myapp:cart' %}">Cart - <span class="cart-amunt">{{request.session.total}}</span> <i class="fa fa-shopping-cart"></i> <span class="product-count">5</span></a>
                    </div>
                </div>
                
            </div>
        </div>
    </div> <!-- End site branding area -->
    
    <div class="mainmenu-area">
        <div class="container">
            <div class="row">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div> 
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'myapp:index' %}">Home</a></li>
                        <li><a href="{% url 'myapp:shop' 'brand' 'Samsung'%}">Shop page</a></li>
                        <li><a href="{% url 'myapp:single-product' '1111' "Computer & Accessrioes" %}">Single product</a></li>
                        <li><a href="{% url 'myapp:cart' %}">Cart</a></li>
                        <li><a href="{% url 'myapp:checkout' %}">Checkout</a></li>
                        <li class="dropdown dropdown-small">
                                <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" href="#"><span class="key">Catageory</span><span class="value"></span><b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a class="cat" href="{% url 'myapp:shop' 'catageory' 'Computer & Accessiories'%}">Computer & Accessrioes</a></li>
                                    <li><a class="cat" href="{% url 'myapp:shop' 'catageory' 'Home & Kitchen'%}">Home & Kitchen</a></li>
                                    <li><a class="cat" href="{% url 'myapp:shop' 'catageory' 'Music & Camera'%}">Music & Camera</a></li>
                                </ul>
                        </li>
                        <li><a href="#">Contact</a></li>
                        <li>
                          <div class="" style="float:right; position:relative;">
                        <form class="form-inline " action="{% url 'myapp:foo-search' %}" method="POST">
                        {% csrf_token %}
                        <input class="form-control" name="name" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success " type="submit" >Search</button>
                        </form>
                        </div>          
                        </li>    

                    </ul>
                                        
                </div>  
            </div>
        </div>
    </div> <!-- End mainmenu area -->


    