EWasteManagement/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp.urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include(myapp.urls,namespace="myapp")),
]

myapp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
<<<<<<< HEAD
urlpatterns = [
    path('',views.index,name='index'),
    path('cart.html',views.cart,name='cart'),
    path('checkout.html',views.checkout,name='checkout'),
    path('shop.html',views.shop,name='shop'),
    path('single-product.html',views.single,name='single-product'),
    ]
=======

app_name = "myapp"

urlpatterns = [
     
     path('index/',views.index,name='index'),
     path('cart/',views.cart,name='cart'),
     path('checkout/',views.checkout,name='checkout'),
     path('shop/<field>/<value>/',views.shop,name='shop'),
     path('single-product/<id>/<catageory>/',views.singleproduct,name='single-product'),
     path('signup/',views.signup,name='signup'),
     path('signin/',views.signin,name='signin'),
     path('signout/',views.signout,name='signout'),
     path('add_to_cart/<int:id>/',views.add_to_card,name='add_to_card'),
     path('item_clear/<int:id>/',views.item_clear,name='item_clear'),
     path('cart_clear/',views.cart_clear,name='cart_clear'),
     path('addProduct/',views.addProduct,name='addProduct'),
     path('search/',views.search,name='foo-search'),
     path('wishlist/<id>/',views.wishlist,name='wishlist'),
     path('showWishlist/',views.show_wishlist,name='showWishlist'),
     path('place_order/',views.place_order,name='place_order'),
     path('',views.index,name='index'),   
    ]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()    
>>>>>>> 6398115 (yes)

cart/models.py
from django.db import models

# Create your models here.

myapp/models.py
from django.db import models
<<<<<<< HEAD

# Create your models here.
class products(models.Model):
    name=models.CharField(max_length=30)
    price=models.IntegerField()
    catageory=models.CharField(max_length=10)
    subcatageory=models.CharField(max_length=10)
    photo = models.ImageField(upload_to='static/img')
    quentity=models.IntegerField()
    description=models.CharField(max_length=200)
    brand=models.CharField(max_length=10)
    longDescription=models.CharField(max_length=1000)


def __str__(self):
    return self.title

=======
from django.contrib.auth.models import User
import uuid

# Create your models here.
class products(models.Model):
    seller=models.ForeignKey(User,on_delete=models.CASCADE,default='root')
    name=models.CharField(max_length=50)
    id=models.IntegerField(primary_key=True)
    price=models.FloatField()
    catageory=models.CharField(max_length=30)
    subCatageory=models.CharField(max_length=30)
    image= models.ImageField(upload_to='static/img')
    quentity=models.PositiveIntegerField()
    description=models.CharField(max_length=200)
    brand=models.CharField(max_length=10)
    longDescription=models.CharField(max_length=1000)
    rating=models.FloatField(default='0')
    offer=models.BooleanField(default=False)
    warrenty=models.BooleanField(default=False)
    age=models.PositiveIntegerField(default=0)

class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product =models.ManyToManyField(products)
    full_name=models.CharField(max_length=30)
    phone=models.IntegerField()
    address1=models.CharField(max_length=30)
    address2=models.CharField(max_length=50)
    city=models.CharField(max_length=15)
    country=models.CharField(max_length=10)
    zipcode=models.IntegerField()
    note=models.CharField(max_length=50)
    def add_product(self,product):
        self.product.add(product)

class Wishlist(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    product =models.ManyToManyField(products)


    def add_product(self,product):
        self.product.add(product)
    
>>>>>>> 6398115 (yes)

myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUp(UserCreationForm):
    username=forms.CharField()
    password1=forms.PasswordInput()
    password2=forms.PasswordInput()
    email=forms.EmailField()
    address=forms.CharField(max_length=200)

    class Meta:
        model=User
        fields=('username','email','password1','password2','address')
        help_texts={
            'email':None,
        }

    def save(self, commit=True):
        user=super(UserCreationForm,self).save(commit=False)
        user.address=self.cleaned_data['address']
        if commit:
            user.save()
        return super().save(commit=commit)    


class ImageHandler(forms.Form):
    image=forms.ImageField()        

cart/views.py
from django.shortcuts import render

# Create your views here.

myapp/views.py
<<<<<<< HEAD
from django.shortcuts import render
from myapp.models import products
# Create your views here.

def index(request):
    return render(request,'index.html')

def cart(request):
    return render(request,'cart.html')

def checkout(request):
    return render(request,'checkout.html')

def shop(request):
    return render(request,'shop.html')

def single(request):
    data= products.objects.all()
    context={
        "data":data
    }
    return render(request,'single-product.html',context)                
=======
from django.shortcuts import render,redirect
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.decorators import login_required
from . forms import SignUp
from django.contrib.auth.forms import UserCreationForm
from myapp.models import products,Wishlist,Order
from cart.cart import Cart
from django.contrib import messages
from myapp.forms import ImageHandler
from cart import cart
# Create your views here.

app_name = "myapp"

def index(request):
    data=products.objects.all()
    return render(request,'myapp/index.html',context={
        "data":data
    })

def place_order(request):
    if request.method == "POST":
        full_name=request.POST.get('full_name')
        phone=request.POST.get('phone')
        address1=request.POST.get('address1')
        address2=request.POST.get('address2')
        city=request.POST.get('city')
        country=request.POST.get('country')
        zipcode=request.POST.get('zipcode')
        note=request.POST.get('note')
        obj=Order.objects.create(user=request.user,full_name=full_name,phone=phone,address1=address1,address2=address2,city=city,country=country,zipcode=zipcode,note=note)
        x= request.session['cart']
        for key,value in x.items():
            if key == '1':
                product=products.objects.get(pk=value.get('product_id'))
                obj.add_product(product)                
        obj.save()
        return redirect('myapp:index')


@login_required(login_url='/myapp/signin')
def wishlist(request,id):
        product = products.objects.get(pk=id)

        try:
            obj = Wishlist.objects.get(user=request.user)
            obj.add_product(product=product)
        except Wishlist.DoesNotExist:
            obj=Wishlist.objects.create(user=request.user)
            obj.add_product(product)

        
        obj.save()
        return redirect('myapp:index')

@login_required(login_url='/myapp/signin')
def show_wishlist(request):
    user=request.user
    try:
        data = Wishlist.objects.get(user=user).product.all()
        print(data)        
        return render(request,'myapp/shop.html',context={
        "data":data
    })     
    except:
         messages.success(request,"Sorry you haven't any product in wishlist")
         return redirect('myapp:index')


    



@login_required(login_url='/myapp/signin')
def add_to_card(request,id):
    cart=Cart(request)
    product=products.objects.get(id=id)
    cart.add(product=product)
    if 'total' not in request.session:
        request.session['total']=0    
    request.session['total']+=getattr(product,'price')
    messages.success(request,"product added to cart")
    return redirect('myapp:cart')

@login_required
def item_clear(request,id):
    cart=Cart(request)
    product=products.objects.get(id=id)
    request.session['total']-=getattr(product,'price')
    cart.remove(product)
    return redirect('myapp:cart')

@login_required
def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    request.session['total']=0
    return redirect('myapp:cart')


def signup(request):
    if request.method == 'POST':
        form=SignUp(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            pw=form.cleaned_data.get('password1')
            user=authenticate(username=username,password=pw)
            login(request,user)
            messages.success(request,"user added successfully")
            return redirect('myapp:index')
    else:
        form=SignUp()
    return render(request,'myapp/signup.html',{'form':form}) 

def signin(request):
    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username,password=password)
        if user is not None:
            login(request,user)
            messages.success(request,"login successful")
            return redirect('myapp:index')
        else:
            return render(request,'myapp/login.html')    
    else:    
        return render(request,'myapp/login.html')
def signout(request):
    logout(request)
    return render(request,'myapp/index.html')  



def cart(request):
    return render(request,'myapp/cart.html')
    
@login_required
def addProduct(request):
    if request.method =='POST':
        imageForm=ImageHandler(request.POST,request.FILES)
        if imageForm.is_valid():
            name=request.POST.get('name')
            brand=request.POST.get('brand')
            description=request.POST.get('description')
            longDescription=request.POST.get('longDescription')
            catageory=request.POST.get('catageory')
            subCatageory=request.POST.get('subCatageory')
            quentity=request.POST.get('quentity')
            image=imageForm.cleaned_data['image']
            price=request.POST.get('price')
            id=request.POST.get('product_id')
            p=products(name=name,price=price,id=id,seller=request.user,description=description,longDescription=longDescription,catageory=catageory,subCatageory=subCatageory,quentity=quentity,rating=0,brand=brand,image=image)
            p.save()
            messages.success(request,"product added successfully")
        return render(request,'myapp/index.html')

    else:
        return render(request,'myapp/addProduct.html')


def checkout(request):
    return render(request,"myapp/checkout.html")
def singleproduct(request,id,catageory):
    data=products.objects.filter(id=id)
    cat=products.objects.filter(catageory=catageory)
    return render(request,'myapp/single-product.html',context={
        "data":data,
        "cat":cat
        })
def shop(request,*args,**kwargs):
    field = kwargs.get('field')
    value = kwargs.get('value')
    if(field=="brand"):
        data=products.objects.filter(brand=value)
    elif(field=="catageory"):   
        data=products.objects.filter(catageory=value)
    else:
        data=products.objects.all()     
    return render(request,'myapp/shop.html',context={
        "data":data
    })        

def search(request):
    if request.method=='POST':
        name=request.POST.get('name')
        data=products.objects.filter(name=name)
        return render(request,'myapp/shop.html',context={
        "data":data
        })
    else:
        return render(request,'myapp/shop.html')

>>>>>>> 6398115 (yes)

myapp/templates/myapp/addProduct.html
{% extends 'base.html'%}

    
{% block content %}


<form method="post" action="{% url 'myapp:addProduct' %}" enctype="multipart/form-data">
{% csrf_token %}
<div class="form-group" style="margin:20px">
<label>ID</label>
<input type="text" name='product_id'><br><br>
 <label>Product Name</label>
<input type="text" name='name'><br><br>
<label>brand</label>
<input type="text" name='brand'><br><br>
<label>Price</label>
<input type="number" name='price'><br><br>
<label>Description</label>
<input type="text" name='description' style="width:100%"><br><br>
<label>Long Description</label>
<input type="textarea" name='longDescription' style="width:100%; height:30%" ><br><br>
<label>categeory</label>

<select name="catageory" id="maincat">
<option selected >Select catageory</option>
<option value="Computer & Accessiories">Computer & Accessiories</option>
<option value="mobile Accessiories">Computer & Accessiories</option>
<option value="Kitchen & Home Appliances">Kitchen & Home Appliances</option>
<option value="Audio">Audio</option>
<option value="Gaming">Gaming</option>
<option value="Storage">Storage</option>
<option value="Tv Audio & cameras">Tv Audio & cameras</option>
<option value="Heating & cooling Appliances">Heating & cooling Appliances</option>
<option value="Smartphone">Smartphone</option>
</select>


<div id="subcat1" class="s">
<label>sub_catageory</label>
<select name="subCatageory" >
<option value="SSD">SSD</option>
<option value="HDD">HDD</option>
<option value="RAM">RAM</option>
<option value="Air conditioner">Air conditioner</option>
<option value="Washing machine">Washing machine</option>
<option value="Others">Others</option>
</select>
</div>


<br>
<label>Quentity</label>
<input type="number" name='quentity'><br><br>
<label>image</label>
<input type="file" name='image'><br><br>
<input type="submit" value="Add product">


</div>
</form>



{%block jquery %}
 

</script>

{%endblock%}
{%endblock content%}

myapp/templates/myapp/index.html
      {% extends "base.html" %}

    
{% block content %}
  {% if messages %}
  
    {% for message in messages %}
    <div class="alert alert-success" role="alert">
        {{ message }}
        <a  class="remove" href="{% url 'myapp:index'  %}" style="float:right">×</a> 
    </div>
    {% endfor %}
  
    {% endif %}

   {%load static%}
    {% load mathfilters %}
   <script src="https://code.jquery.com/jquery.min.js"></script>
    
    <div class="slider-area">
        	<!-- Slider -->
			<div class="block-slider block-slider4">
				<ul class="" id="bxslider-home4">
					<li>
						<img src="{% static 'img/h4-slide.png' %}" alt="Slide">
						<div class="caption-group">
							<h2 class="caption title">
								iPhone <span class="primary">6 <strong>Plus</strong></span>
							</h2>
							<h4 class="caption subtitle">Dual SIM</h4>
							<a class="caption button-radius" href="#"><span class="icon"></span>Shop now</a>
						</div>
					</li>
					<li><img src="{% static 'img/h4-slide2.png' %}" alt="Slide">
						<div class="caption-group">
							<h2 class="caption title">
								by one, get one <span class="primary">50% <strong>off</strong></span>
							</h2>
							<h4 class="caption subtitle">school supplies & backpacks.*</h4>
							<a class="caption button-radius" href="#"><span class="icon"></span>Shop now</a>
						</div>
					</li>
					<li><img src="{% static 'img/h4-slide3.png' %}" alt="Slide">
						<div class="caption-group">
							<h2 class="caption title">
								Apple <span class="primary">Store <strong>Ipod</strong></span>
							</h2>
							<h4 class="caption subtitle">Select Item</h4>
							<a class="caption button-radius" href="#"><span class="icon"></span>Shop now</a>
						</div>
					</li>
					<li><img src="{% static 'img/h4-slide4.png' %}" alt="Slide">
						<div class="caption-group">
						  <h2 class="caption title">
								Apple <span class="primary">Store <strong>Ipod</strong></span>
							</h2>
							<h4 class="caption subtitle">& Phone</h4>
							<a class="caption button-radius" href="#"><span class="icon"></span>Shop now</a>
						</div>
					</li>
				</ul>
			</div>
			<!-- ./Slider -->
    </div> <!-- End slider area -->
    
    <div class="promo-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <div class="single-promo promo1">
                        <i class="fa fa-refresh"></i>
                        <p>30 Days return</p>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="single-promo promo2">
                        <i class="fa fa-truck"></i>
                        <p>Free shipping</p>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="single-promo promo3">
                        <i class="fa fa-lock"></i>
                        <p>Secure payments</p>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6" >
                    <div class="single-promo promo4" style="background-color: green;">
                        <i class="fa fa-tree"></i>
                        <p>Go Green</p>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End promo area -->
    
    <div class="maincontent-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="latest-product">
                        <h2 class="section-title">Latest Products</h2>
                        <div class="product-carousel">
                        {% for obj in data %}
                            <div class="single-product">
                                <div class="product-f-image">
                                    <img src="{{obj.image.url}}" alt="" style="width:200px;height:200px;">
                                    <div class="product-hover">
                                        <a href="{% url 'myapp:add_to_card' obj.id %}" class="add-to-cart-link"><i class="fa fa-shopping-cart"></i> Add to cart</a>
                                        <a href="{% url 'myapp:single-product' obj.id obj.catageory %}" class="view-details-link"><i class="fa fa-link"></i> See details</a>
                                    </div>
                                </div>
                                
                                <h2><a href="single-product.html">{{obj.name}} </a></h2>
                                
                                <div class="product-carousel-price">
                                    <ins>{{obj.price}}</ins> <del>$100.00</del> <a href="{% url 'myapp:wishlist' obj.id %}"><i class="fa fa-heart" style="color:black"></i></a> 
                                </div> 
                            </div>
                         {%endfor%}
                           
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End main content area -->
    
    <div class="brands-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="brand-wrapper">
                        <div class="brand-list">
                            <img src="{% static 'img/brand1.png' %}" alt="">
                            <img src="{% static 'img/brand2.png' %}" alt="">
                            <img src="{% static 'img/brand3.png' %}" alt="">
                            <img src="{% static 'img/brand4.png' %}" alt="">
                            <img src="{% static 'img/brand5.png' %}" alt="">
                                                      
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End brands area -->
    
     
         <div class="maincontent-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="latest-product">
                        <h2 class="section-title">Top Seller</h2>
                        <div class="product-carousel">
                        {% for obj in data %}
                            <div class="single-product">
                                <div class="product-f-image">
                                    <img src="{{obj.image.url}}" alt="" style="width:200px;height:200px;">
                                    <div class="product-hover">
                                        <a href="{% url 'myapp:add_to_card' obj.id %}" class="add-to-cart-link"><i class="fa fa-shopping-cart"></i> Add to cart</a>
                                        <a href="{% url 'myapp:single-product' obj.id obj.catageory %}" class="view-details-link"><i class="fa fa-link"></i> See details</a>
                                    </div>
                                </div>
                                
                                <h2><a href="single-product.html">{{obj.name}}</a></h2>
                                
                                <div class="product-carousel-price">
                                    <ins>{{obj.price}}</ins> <del>$100.00</del>
                                </div> 
                            </div>
                         {%endfor%}
                           
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End main content area -->
    







{%endblock content%}

myapp/templates/myapp/login.html
<!doctype html>
<html lang="en">
  <head>
   {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Signin Template for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sign-in/">

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'signin.css' %}" rel="stylesheet">
     <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %} ">
    
   
  </head>

  <body class="text-center">
    <form class="form-signin" action="{% url 'myapp:signin' %}" method="post">
        {% csrf_token %}
      <img class="mb-4" src="{% static 'img/logo.png' %}" alt="" >
      <div style="width:300px; margin:auto;">
      <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
      <label for="inputEmail" class="sr-only">Username</label>
      <input type="text" id="inputEmail" name="username" class="form-control" placeholder="Username" required autofocus >
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required>
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      <p class="mt-5 mb-3 text-muted">&copy; 2020-2021</p>
    </form>
    </div>
  </body>
</html>

myapp/templates/myapp/shop.html
{% extends 'base.html'%}
 
{% block content %}

 <div class="product-big-title-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="product-bit-title text-center">
                        <h2>Shop</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    
    <div class="single-product-area">
        
        <div class="container">
            <div class="row">
            {% for instance in data  %}
                <div class="col-md-3 col-sm-6">
                    <div class="single-shop-product">
                        <div class="product-upper">
                            <img src="{{instance.image.url}}" alt="" style="width:200px;height:200px;">
                        </div>
                        <h2><a href="">{{instance.name}}</a></h2>
                        <div class="product-carousel-price">
                            <ins>{{instance.price}}</ins> <del>$999.00</del>
                        </div>  
                        
                        <div class="product-option-shop">
                            <a class="add_to_cart_button" data-quantity="1" data-product_sku="" data-product_id="70" rel="nofollow" href="{% url 'myapp:add_to_card' instance.id %}">Add to cart</a>
                        </div>                       
                    </div>
                </div>
            {%endfor%}
            </div>
            
            <div class="row">
                <div class="col-md-12">
                    <div class="product-pagination text-center">
                        <nav>
                          <ul class="pagination">
                            <li>
                              <a href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                              </a>
                            </li>
                            <li><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">4</a></li>
                            <li><a href="#">5</a></li>
                            <li>
                              <a href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                              </a>
                            </li>
                          </ul>
                        </nav>                        
                    </div>
                </div>
            </div>
        </div>
    </div>

{% include "footer.html" %}
   
    <!-- Latest jQuery form server -->
  

{%endblock content%}
    

myapp/templates/myapp/signup.html
{% extends 'base.html'%}

    
{% block content %}

<h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit">Sign up</button>
  </form>


{%endblock content%}